version: "3.8"

services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hapi-demo.rule=Host(`hapi-demo.local`)"
      - "traefik.http.services.hapi-demo.loadbalancer.server.port=3000"
    networks:
      - web
    expose:
      - "3000"

  traefik:
    image: "traefik:v3.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    external: true
