# fly.toml app configuration file generated for hapi-demo on 2023-10-29T22:20:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hapi-demo"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[deploy]
strategy = "bluegreen"

[env]
PORT = "3000"
SERVER_HOSTNAME = "0.0.0.0"

[[services]]
protocol = "tcp"
internal_port = 3000
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/"
protocol = "http"
